-- Chạy trong Supabase SQL Editor.
-- Bảng blog_posts cho Blog Content Management (admin) và trang blog public.

CREATE TABLE IF NOT EXISTS public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  excerpt TEXT,
  body TEXT,
  category TEXT,
  image_url TEXT,
  author TEXT,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger: cập nhật updated_at khi sửa row
CREATE OR REPLACE FUNCTION public.set_blog_posts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS blog_posts_updated_at ON public.blog_posts;
CREATE TRIGGER blog_posts_updated_at
  BEFORE UPDATE ON public.blog_posts
  FOR EACH ROW EXECUTE FUNCTION public.set_blog_posts_updated_at();

ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;

-- Admin: full access (SELECT, INSERT, UPDATE, DELETE)
CREATE POLICY "Admin full access blog_posts" ON public.blog_posts
  FOR ALL TO authenticated
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Public: chỉ đọc bài đã published
CREATE POLICY "Public read published blog_posts" ON public.blog_posts
  FOR SELECT TO anon, authenticated
  USING (status = 'published');

-- 10 Blog Posts mẫu: chạy trong SQL Editor sau khi đã tạo bảng + RLS.
-- Chỉ chạy một lần (slug unique); nếu đã có bài trùng slug thì xóa bớt hoặc đổi slug.
INSERT INTO public.blog_posts (slug, title, excerpt, body, category, image_url, author, status) VALUES
('huong-dan-bep-zero-waste', 'Hướng dẫn bếp Zero Waste cho gia đình Việt', 'Chuyển sang bếp không rác thải không khó. Chỉ cần vài thay đổi nhỏ trong thói quen mua sắm và nấu nướng.', '<p>Bắt đầu bằng việc mua thực phẩm theo lượng vừa đủ, tận dụng túi vải khi đi chợ và ưu tiên sản phẩm đóng gói tái chế hoặc có thể tái sử dụng.</p><p>Phân loại rác hữu cơ để ủ compost tại nhà giúp giảm đáng kể lượng rác thải ra môi trường.</p>', 'Sustainability', NULL, 'ReenCo', 'published'),
('5-cach-tai-che-ong-hut-co', '5 cách tái chế ống hút cỏ bền vững', 'Ống hút cỏ dùng xong đừng vứt. Từ làm phân compost đến đồ thủ công, cùng khám phá cách tận dụng tối đa.', '<p>1. Bỏ vào thùng ủ compost cùng rác hữu cơ.</p><p>2. Làm giá đỡ cây mini.</p><p>3. Dùng làm que khuấy tự nhiên.</p><p>4. Kết hợp với vải vụn làm đồ trang trí.</p><p>5. Nghiền nhỏ trộn đất trồng cây.</p>', 'Tips', NULL, 'ReenCo', 'published'),
('vi-sao-nen-dung-ong-hut-co', 'Vì sao nên dùng ống hút cỏ thay ống hút nhựa?', 'Ống hút cỏ tự nhiên, phân hủy hoàn toàn và thân thiện với sức khỏe. Đây là lựa chọn bền vững cho mọi ly uống.', '<p>Ống hút cỏ được làm từ cây cỏ bàng, không qua hóa chất, dùng một lần rồi phân hủy trong vài tháng.</p><p>So với ống nhựa tồn tại hàng trăm năm, ống hút cỏ giúp giảm rác thải nhựa và ô nhiễm đại dương.</p>', 'Sustainability', NULL, 'ReenCo', 'published'),
('bi-quyet-mua-sam-xanh', 'Bí quyết mua sắm xanh không tốn kém', 'Mua sắm bền vững không có nghĩa là phải chi nhiều tiền. Chỉ cần ưu tiên đúng thứ và nói không với túi nilon.', '<p>Mang theo túi vải, hộp đựng khi đi chợ. Chọn sản phẩm có bao bì tối giản hoặc có thể tái chế.</p><p>Ưu tiên hàng nội địa, theo mùa để giảm khí thải vận chuyển và hỗ trợ nông dân địa phương.</p>', 'Lifestyle', NULL, 'ReenCo', 'published'),
('lam-sach-nha-bang-nguyen-lieu-tu-nhien', 'Làm sạch nhà bằng nguyên liệu tự nhiên', 'Giấm, baking soda và chanh là đủ để nhà cửa sạch bong mà không cần hóa chất độc hại.', '<p>Pha giấm với nước để lau kính, bếp. Baking soda rắc lên bề mặt cần tẩy rồi chà nhẹ.</p><p>Chanh sử dụng khử mùi, tẩy vết ố. Vừa an toàn cho trẻ và thú cưng vừa tiết kiệm.</p>', 'DIY', NULL, 'ReenCo', 'published'),
('du-lich-khong-nhua-2024', 'Du lịch không nhựa: tips cho chuyến đi xanh', 'Du lịch không cần hủy hoại môi trường. Mang theo bình nước, ống hút cỏ và túi vải cho mọi chuyến đi.', '<p>Chuẩn bị bộ dụng cụ ăn uống cá nhân: bình nước, ống hút cỏ, hộp đựng nhỏ.</p><p>Từ chối túi nilon và ống hút nhựa tại quán. Chọn chỗ ở và tour có cam kết giảm rác thải.</p>', 'Travel', NULL, 'ReenCo', 'published'),
('tieu-chuan-phan-huy-sinh-hoc', 'Hiểu về tiêu chuẩn phân hủy sinh học', 'Không phải nhãn "xanh" nào cũng giống nhau. Cùng tìm hiểu chứng nhận nào thực sự đáng tin khi chọn sản phẩm.', '<p>Compostable và biodegradable khác nhau: compostable thường cần điều kiện ủ công nghiệp.</p><p>Ống hút cỏ tự nhiên phân hủy trong môi trường thường, không cần xử lý đặc biệt.</p>', 'Sustainability', NULL, 'ReenCo', 'published'),
('xu-huong-an-uong-ben-vung-tai-viet-nam', 'Xu hướng ăn uống bền vững tại Việt Nam', 'Các quán cafe và nhà hàng đang dần chuyển sang ống hút cỏ, ly giấy và hộp phân hủy. Cùng điểm qua xu hướng.', '<p>Ngày càng nhiều thương hiệu cam kết giảm nhựa một lần, ưu tiên ống hút cỏ và bao bì thân thiện môi trường.</p><p>Khách hàng có thể góp phần bằng cách ưu tiên những địa điểm xanh và từ chối đồ nhựa dùng một lần.</p>', 'Lifestyle', NULL, 'ReenCo', 'published'),
('u-compost-tai-nha-khong-co-vuon', 'Ủ compost tại nhà khi không có vườn', 'Không có sân vườn vẫn ủ được phân hữu cơ. Phương pháp vermicompost và bokashi phù hợp căn hộ.', '<p>Vermicompost dùng giun đỏ, thùng nhỏ đặt trong bếp hoặc ban công.</p><p>Bokashi dùng men ủ, kín mùi, phù hợp không gian hẹp. Rác hữu cơ sau ủ có thể đem cho nông dân hoặc trồng cây trong chậu.</p>', 'Guides', NULL, 'ReenCo', 'published'),
('reco-gioi-thieu-thuong-hieu', 'ReenCo – Thương hiệu ống hút cỏ Việt', 'ReenCo ra đời với mong muốn mang ống hút cỏ chất lượng, nguồn gốc rõ ràng đến mọi bàn ăn và quán cafe tại Việt Nam.', '<p>Chúng tôi hợp tác với người dân vùng đồng bằng để thu mua cỏ bàng, tạo thu nhập bền vững và giữ nghề truyền thống.</p><p>Mỗi sản phẩm đều được kiểm tra kỹ, đảm bảo an toàn và thân thiện môi trường từ khâu nguyên liệu đến đóng gói.</p>', 'About', NULL, 'ReenCo', 'published');
