-- Chạy trong Supabase SQL Editor.
-- Bảng coupons cho admin Marketing (tạo mã giảm giá).

CREATE TABLE IF NOT EXISTS public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  description TEXT,
  discount_type TEXT NOT NULL DEFAULT 'percentage' CHECK (discount_type IN ('percentage', 'fixed_cart')),
  discount_value DECIMAL(15, 2) NOT NULL DEFAULT 0,
  usage_limit INTEGER,
  usage_count INTEGER DEFAULT 0,
  start_date DATE,
  end_date DATE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- Chỉ admin mới được xem / thêm / sửa / xóa
CREATE POLICY "Admin full access coupons" ON public.coupons
  FOR ALL TO authenticated
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Public có thể đọc coupon active (để áp dụng tại checkout) - bật nếu cần
-- CREATE POLICY "Public read active coupons" ON public.coupons
--   FOR SELECT USING (is_active = true AND (end_date IS NULL OR end_date >= CURRENT_DATE));
