-- Chạy trong Supabase SQL Editor.
-- Bảng customers cho admin CRM (thêm khách hàng thủ công, không cần đăng ký).

CREATE TABLE IF NOT EXISTS public.customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Chỉ admin mới được xem / thêm / sửa / xóa
CREATE POLICY "Admin full access customers" ON public.customers
  FOR ALL TO authenticated
  USING ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin')
  WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'admin');

-- Public không đọc customers (chỉ admin)
-- Nếu cần user đọc: thêm policy FOR SELECT USING (true);
